module.exports = {
  apps: [
    {
      // Frontend PWA
      name: 'myid-pwa',
      script: 'node_modules/next/dist/bin/next',
      args: 'start',
      cwd: '/perform1/srv/work/myid-app',
      instances: 1,
      exec_mode: 'cluster',
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 6230,
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 6230,
      },
      error_file: 'logs/pwa-error.log',
      out_file: 'logs/pwa-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      // Backend HSM Service
      name: 'myid-hsm',
      script: 'server.mjs',
      cwd: '/perform1/srv/work/myid-app/backend',
      instances: 1,
      exec_mode: 'cluster',
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: 6321,
        HSM_HOST: '172.27.127.129',
        HSM_PORT: 3001,
        DB_HOST: 'db.pocket.one',
        DB_PORT: 5432,
        DB_NAME: 'myid_africa',
        DB_USER: 'qm4sfgp38xasdyl3sy',
        DB_PASSWORD: '',
        DB_SSL: 'true',
        REDIS_HOST: '127.0.0.1',
        REDIS_PORT_1: 7100,
        JWT_EXPIRES_IN: '24h',
        WEBAUTHN_RP_NAME: 'myID.africa',
        WEBAUTHN_RP_ID: 'localhost',
        WEBAUTHN_ORIGIN: 'http://localhost:3000',
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 6321,
        DB_HOST: 'db.pocket.one',
        DB_PORT: 5432,
        DB_NAME: 'myid_africa',
        DB_USER: 'qm4sfgp38xasdyl3sy',
        DB_PASSWORD: '',
        DB_SSL: 'true',
        REDIS_HOST: '127.0.0.1',
        REDIS_PORT_1: 7100,
      },
      error_file: 'logs/hsm-error.log',
      out_file: 'logs/hsm-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      // ngrok - External HTTPS tunnel with custom domain
      name: 'myid-ngrok',
      script: 'ngrok',
      args: 'http --domain=pwa.myid.africa 6230 --log stdout',
      cwd: '/perform1/srv/work/myid-app',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: 'logs/ngrok-error.log',
      out_file: 'logs/ngrok-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],

  deploy: {
    production: {
      user: 'deploy',
      host: ['nv2', 'nv3'],
      ref: 'origin/main',
      repo: 'git@github.com:yourorg/myid-africa.git',
      path: '/srv/work/myid-app',
      'post-deploy': 'npm install && npm run build && pm2 reload ecosystem.config.cjs --env production',
      env: {
        NODE_ENV: 'production',
      },
    },
  },
};
